export const layersInit = [
  {
    layer: "pch",
    show: false,
    name: "Границы ПЧ",
    visible: "visible",
    disabled: false,
    id: 0,
  },
  {
    layer: "shch",
    show: false,
    name: "Границы ШЧ",
    visible: "visible",
    disabled: false,
    id: 1,
  },
  {
    layer: "vchd",
    show: false,
    name: "Границы ВЧД",
    visible: "visible",
    disabled: false,
    id: 2,
  },
  {
    layer: "ech",
    show: false,
    name: "Границы ЭЧ",
    visible: "visible",
    disabled: false,
    id: 3,
  },
  {
    layer: "dnc",
    show: false,
    name: "Диспетчерские участки",
    visible: "visible",
    disabled: false,
    id: 4,
  },
  {
    layer: "current",
    show: false,
    name: "Электрификация",
    visible: "visible",
    disabled: false,
    id: 5,
  },

  {
    layer: "loco",
    show: false,
    name: "Схема тягового обслуживания локомотивами (грузовые поезда)",
    visible: "visible",
    disabled: false,
    id: 6,
  },
  {
    layer: "loco_team dolb",
    show: false,
    name:
      "Схема тягового обслуживания локомотивными бригадами (грузовые поезда)",
    visible: "visible",
    disabled: false,
    id: 7,
  },
  {
    layer: "loco_pass",
    show: false,
    name: "Схема тягового обслуживания локомотивами (пассажирские поезда)",
    visible: "visible",
    disabled: false,
    id: 8,
  },
  {
    layer: "loco_team_pass",
    show: false,
    name:
      "Схема тягового обслуживания локомотивными бригадами (пассажирские поезда)",
    visible: "visible",
    disabled: false,
    id: 9,
  },
  {
    layer: "spec_trains",
    show: false,
    name: "Восстановительные и пожарные поезда",
    visible: "visible",
    disabled: false,
    id: 10,
  },
  {
    layer: "dtv",
    show: false,
    name: "ДТВУ",
    visible: "visible",
    disabled: false,
    id: 11,
  },

  {
    layer: "ngch",
    show: false,
    name: "НГЧ, дистанция гражданских сооружений",
    visible: "visible",
    disabled: false,
    id: 12,
  },
  {
    layer: "rcs",
    show: false,
    name: "Границы РЦС, поездная радиосвязь",
    visible: "visible",
    disabled: false,
    id: 13,
  },

  {
    layer: "mls",
    show: false,
    name: "Границы РЦС, линии связи",
    visible: "visible",
    disabled: false,
    id: 14,
  },
  {
    layer: "trains_distantions",
    show: true,
    name: "Штормовое предупреждение",
    visible: "visible",
    disabled: false,
    id: 15,
  },

  {
    layer: "snow_tech",
    show: false,
    name: "Снегоуборочная техника",
    visible: "visible",
    disabled: false,
    id: 16,
  },
  {
    layer: "weather_st",
    show: false,
    name: "Фактическая погода",
    visible: "visible",
    disabled: false,
    id: 17,
  },
  {
    layer: "bridges",
    show: false,
    name: "Искусственные сооружения",
    visible: "visible",
    disabled: false,
    id: 18,
  },
  {
    layer: "tubes",
    show: false,
    name: "трубы ИССО",
    visible: "visible",
    disabled: false,
    id: 19,
  },
  {
    layer: "health_org",
    show: false,
    name: "здоровый образ жизни",
    visible: "visible",
    disabled: false,
    id: 20,
  },
];
